version: '3.8'

services:
  web:
    build:
      context: ./project
      args:
        SETUP_SCRIPT: finalize.dev.sh
        SCRIPTS_LOCATION: scripts
      dockerfile: ../dockerfiles/Dockerfile
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - ./project/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./enviroments/.env.dev
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost" ]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    pid: "host"
