name: CI-Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    container: 
    steps:
      - uses: actions/checkout@v1

      - name: Build the stack
        run: |
          docker-compose up --build -d
          cd project
          /bin/sh scripts/finalize.dev.sh
          scripts/test.sh