name: CI-Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    container: 
    steps:
      - uses: actions/checkout@v1

      - name: Build the stack
        run: docker-compose up --build -d 

      - name: Run setup script
        working-directory: ./project
        run: /bin/sh project/scripts/finalize.dev.sh

      - name: Run python tests
        run: scripts/test.sh